import type { APIRoute } from 'astro';
import { getCollection } from 'astro:content';
import { knowledgeArticles } from '../data/knowledge-articles';
import { KNOWLEDGE_ARTICLES_RU } from '../content/i18n/knowledge/articles-ru';
import { framelessCategories } from '../data/frameless-catalog';
import { facadeCategories } from '../data/facade-catalog';
import { doorCategories } from '../data/door-catalog';
import { railingCategories } from '../data/railing-catalog';
import { BUSINESS_HUB, businessPages, businessPath } from '../data/business-pages';
import { CANOPY_HUB, canopyCategories } from '../data/canopy-catalog';
import { PARTITION_HUB, partitionCategories } from '../data/partition-catalog';
import { mirrorTypes } from '../data/mirror-types';
import { canopyCategoriesRu } from '../data/ru/canopy-catalog.ru';
import { railingCategoriesRu } from '../data/ru/railing-catalog.ru';
import { partitionCategoriesRu } from '../data/ru/partition-catalog.ru';
import { RAILINGS_HUB } from '../data/railing-catalog';
import { DOORS_HUB } from '../data/door-catalog';
import { framelessCategoriesRu } from '../data/ru/frameless-catalog.ru';
import { doorCategoriesRu } from '../data/ru/door-catalog.ru';
import { facadeCategoriesRu } from '../data/ru/facade-catalog.ru';
import { businessPagesRu } from '../data/ru/business-pages.ru';
import { hasProjectRu } from '../data/ru/projects.ru';
const pages = import.meta.glob('./**/*.astro');
// uk/* pages are non-canonical duplicates of the unprefixed root pages (their own
// canonical tag points at the unprefixed URL), so they must not be submitted separately.
const excludedLocales = /^\.\/(en|de|uk)(?:\/|$)/;
// These ru/* pages redirect straight back to the unprefixed (uk) URL and never render real
// Russian content, so they must not be submitted to search engines as indexable RU pages.
// ru/about, ru/catalog, ru/projects and ru/poslugy are NOT in this list: all render real,
// locale-branched content on the same shared template as their uk counterpart and must be
// indexed as real RU pages. ru/services no longer exists as a page at all (deleted, not a
// redirect), so it needs no exclusion entry here.
const excludedRuStubs = /^\.\/ru\/(cart|compare|quote)(?:\/|$)/;
// ru/catalog/piddon is a separate, still-a-redirect-stub page nested under the now-real
// ru/catalog/ hub, so it needs its own exact-path exclusion instead of matching on "catalog".
const excludedRuNestedStub = /^\.\/ru\/catalog\/piddon\/index\.astro$/;
export const GET: APIRoute = async ({ site }) => {
  const origin=(site ?? new URL('https://space-glass.com.ua')).origin;
  const projects = await getCollection('projects', ({ data }) => data.status === 'published' && data.locale === 'uk');
  // Only the /project/{slug}/ static override (e.g. ./project/mizhkimnatni-peregorodky-v-styli-loft-zhk-atlant-m-kyyiv/index.astro) is
  // excluded here — it's already covered by projectUrls below. This must NOT match
  // ./ru/project/index.astro, which is the real RU projects hub and belongs in fileUrls.
  const excludedProjectOverride = /^\.\/projects\//;
  const fileUrls=Object.keys(pages).filter(path=>!excludedLocales.test(path)&&!excludedRuStubs.test(path)&&!excludedRuNestedStub.test(path)&&!path.startsWith('./catalog/dushovi-piddony/')&&!path.includes('[')&&!path.includes('/404.astro')&&!path.includes('/ui-kit/')&&!path.includes('/project-print/')&&!path.includes('/proposal.astro')&&!path.includes('/thank-you.astro')&&!path.includes('/cart/')&&!path.includes('/compare/')&&!path.includes('/wishlist/')&&!excludedProjectOverride.test(path)).map(path=>path.replace(/^\.\//,'/').replace(/index\.astro$/, '').replace(/\.astro$/, '/'));
  const projectUrls = ['/project/', ...projects.map(({ data }) => `/project/${data.slug}/`)];
  // RU project pages — dynamic src/pages/ru/project/[slug].astro (the /ru/project/ hub is in fileUrls).
  const ruProjectUrls = projects.filter(({ data }) => hasProjectRu(data.slug)).map(({ data }) => `/ru/project/${data.slug}/`);

  // Dynamic Knowledge routes are generated by [slug].astro and therefore are
  // intentionally absent from import.meta.glob's static file URL discovery.
  const knowledgeUrls = knowledgeArticles.map(
    ({ slug }) => `/knowledge/${slug}/`
  );

  // Only RU articles with a real translated dataset are indexable.
  const ruKnowledgeUrls = Object.keys(KNOWLEDGE_ARTICLES_RU).map(
    (slug) => `/ru/knowledge/${slug}/`
  );

  // The old programmatic /poslugy/{category}/ silo no longer renders pages (every section
  // moved to its own hub), so its URLs are not listed. Sitemap = canonical 200 pages only.

  // RU child pages of the translated sections — dynamic [slug].astro routes under /ru/.
  const ruSectionUrls = [
    ...canopyCategoriesRu.map(({ slug }) => `/ru/sklyani-kozyrky/${slug}/`),
    ...railingCategoriesRu.filter(({ path }) => path.startsWith(RAILINGS_HUB)).map(({ slug }) => `/ru/sklyani-ohorozhi/${slug}/`),
    ...partitionCategoriesRu.map(({ slug }) => `/ru/sklyani-perehorodky/${slug}/`),
    ...mirrorTypes.map(({ href }) => `/ru${href}`),
    ...framelessCategoriesRu.map(({ slug }) => `/ru/bezramne-sklinnya/${slug}/`),
    ...doorCategoriesRu.filter(({ path }) => path.startsWith(DOORS_HUB)).map(({ slug }) => `/ru/sklyani-dveri/${slug}/`),
    ...facadeCategoriesRu.map(({ path }) => `/ru${path}`),
    ...businessPagesRu.map(({ slug }) => `/ru${businessPath(slug)}`)
  ];

  // Mirror child pages under the /dzerkala/ MASTER — generated by
  // src/pages/dzerkala/[type].astro (dynamic route, so not picked up by the
  // static file glob above).
  const mirrorChildUrls = mirrorTypes.map(({ href }) => href);

  // Frameless glazing child pages — src/pages/bezramne-sklinnya/[slug].astro
  // (the old programmatic pages of this silo are replaced by these).
  const framelessUrls = framelessCategories.map(({ path }) => path);
  const facadeUrls = facadeCategories.map(({ path }) => path);
  const doorUrls = doorCategories.map(({ path }) => path);
  const railingUrls = railingCategories.map(({ path }) => path);
  const canopyUrls = [CANOPY_HUB, ...canopyCategories.map(({ path }) => path)];
  const partitionUrls = [PARTITION_HUB, ...partitionCategories.map(({ path }) => path)];
  const businessUrls = [BUSINESS_HUB, ...businessPages.map(({ slug }) => businessPath(slug))];

  const urls = [...new Set([
    ...fileUrls,
    ...projectUrls,
    ...ruProjectUrls,
    ...knowledgeUrls,
    ...ruKnowledgeUrls,
    ...ruSectionUrls,
    ...mirrorChildUrls,
    ...framelessUrls,
    ...facadeUrls,
    ...doorUrls,
    ...railingUrls,
    ...businessUrls,
    ...canopyUrls,
    ...partitionUrls,
  ])].sort();
  const body=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(path=>`\n  <url><loc>${origin}${path}</loc><changefreq>${path==='/'?'weekly':'monthly'}</changefreq><priority>${path==='/'?'1.0':'0.7'}</priority></url>`).join('')}\n</urlset>`;
  return new Response(body,{headers:{'content-type':'application/xml; charset=utf-8','cache-control':'public, max-age=3600'}});
};
